version: '3'

services:
  nexus:
    image: sonatype/nexus3
    ports:
      - "7081:8081"
      - "7085:8085"
      - "8442:8442"
    volumes:
      - ./nexus-data:/nexus/data
    restart: always

volumes:
  nexus-data: